# Setup
name:                Get Weather Info
title:               Get Weather Info
tagline:             Get weather in your location.
author:              Sazzad Hossain
author_email:        sazzad@beeback.io
url:                 https://iamshipon1988.github.io/getweather/
baseurl:             https://iamshipon1988.github.io/getweather/
permalink:           pretty
exclude:             [README.markdown]
analytics_id:        "UA-104952515-1"

# SEO information
seo:
    description: "Discover photogenic locations"
    keywords: "bootstrap, admin, theme, panel, administration, material"

# Owner/author information
owner:
    name:           EyePop App
    avatar:         logo.png
    bio:            "Discover photogenic locations."
    email:          sazzad@beeback.io
    twitter:        iamshipon1988
    github:         iamshipon1988
    instagram:      comingsoon
    location:       "New York, NY"


# Custom vars
version:             0.1.0
github:
  repo:


# Plugins
plugins:
- jekyll-sitemap
