# Setup
name:                Get Weather Info
title:               Get Weather Info
tagline:             Get weather in your location.
author:              Sazzad Hossain
author_email:        sazzad@sazzad.me
url:                 http://localhost:4000/
baseurl:             ''
permalink:           pretty
exclude:             [README.markdown]
analytics_id:        ""

# SEO information
seo:
    description: "Get weather in your location."
    keywords: "weather, temperature, heat, cold, snow, rain"

# Owner/author information
owner:
    name:           EyePop App
    avatar:         logo.png
    bio:            "Get weather in your location."
    email:          sazzad@sazzad.me
    twitter:        iamshipon1988
    github:         iamshipon1988
    location:       "New York, NY"


# Custom vars
version:             0.1.0
github:
  repo:


# Plugins
plugins:
- jekyll-sitemap
